version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /home/junior/.jellyfin/config:/config
      - /home/junior/.jellyfin/cache:/cache
      - type: bind
        source: /mnt/MEDIA/Movies
        target: /media/movies
        read_only: true
      - type: bind
        source: /mnt/MEDIA/Shows
        target: /media/shows
        read_only: true
      - type: bind
        source: /mnt/MEDIA/Music
        target: /media/music
        read_only: true
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
