k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: true
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 1000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: true
    showTime: true
  currentContext: arn:xxxxxx:cluster/xxxxxx
  currentCluster: arn:xxxxxx:cluster/xxxxxx
  keepMissingClusters: false
  clusters:
    arn:xxxxxx:cluster/xxxxxx:
      namespace:
        active: app-test-x
        lockFavorites: true
        favorites:
        - app-test-x
        - app-test-y
        - app-prod-x
        - app-prod-y
      view:
        active: pods
      #skin: stock
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s
  disablePodCounting: false
